### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by esmaeelE** [sajaddp/list-of-cities-in-Iran#23]
تصویر نقشهٔ ایران کامل نیست. دریای خزر و خلیج فارس و دریای عمان قسمتی از نقشهٔ ایران است.

لطفا اصلاح کنید.
فکر می‌کنم فرمانداری‌ها در شهرهای مجاور ساحل روی قسمت‌های آبی کنترل دارند.

**Comment by sajaddp** [comment]
@esmaeelE 
از پیشنهاد شما متشکرم. اما هدف مخزن گردآوری لیست شهرهای ایران هست و تصویر تنها برای زیبایی قرار گرفته.
