### ISSUE TITLE
Adding Longituge and Latitude to cities and provinces

### ISSUE THREAD

**Issue by maktoobgar** [sajaddp/list-of-cities-in-Iran#35]
Hello,

I was wondering if it would be allowed if I could add longitude and latitude to these cities and provinces.
In my previous 2 or 3 days ago, I was trying(and still am) to achieve a goal to actually have a list of all cities and provinces plus their geolocations on the map and I found two great resources and one not very great API to gather that information for the matter and I gotta say this repository is the most reliable one of them all and that is the reason I want to complete it even feather and add those geolocations to it.
I'm about 80% done but it takes time to get to 100% because of having to do it all by hand from 80% forward.

Anyways, all I wanted to say is that, is it welcome for these geolocational changes on the repository on cities and provinces from me in future?

Best regards,
MH

**Comment by sajaddp** [comment]
Yes, I would definitely appreciate it if it's accurate.
The only important thing is that we have to update and test the examples for all the languages in the repository. Because many people directly use sample codes.

**Comment by maktoobgar** [comment]
Plus I translated city names and province names in English(ChatGPT involved in the process) and I won't guarantee all of them are good and correct because it is AI and AI does a lot of mistakes as we all know but I guarantee that I did my best to find all mess ups of ChatGPT. (I did review them two times, fixed some mess ups by hand and prompted multiple times to get the exact translations, I did what I could 😅)

**Comment by maktoobgar** [comment]
> Yes, I would definitely appreciate it if it's accurate. The only important thing is that we have to update and test the examples for all the languages in the repository. Because many people directly use sample codes.

Great, I checked some of the lats and lngs of some cities at random and I always got the right spot, plus it seems to be all fine and done accurately but If somebody could actually check them too, that would be awesome.

**Comment by sajaddp** [comment]
If adding the English names of the cities, it is necessary to add the English slog.
You should also ensure that the English name and English slog are not duplicated. Because some cities have similar names.
Also, chatGPT answers are wrong for geographic location and are correct only for some cities in Iran.
You create a PR when you're done, I'll check it out.

**Comment by maktoobgar** [comment]
> If adding the English names of the cities, it is necessary to add the English slog. You should also ensure that the English name and English slog are not duplicated. Because some cities have similar names. Also, chatGPT answers are wrong for geographic location and are correct only for some cities in Iran. You create a PR when you're done, I'll check it out.

Ok... So I'm gonna just finish the remaining geolocations and when it is fully done, a PR will be on the repository with all lats and lngs of cities and provinces.

By the way, thank you for putting your time and effort into this.
You guys have done a massive job.
