### ISSUE TITLE
ترتیب استان ها بر اساس  ترتیب فایل مرکز آمار

### ISSUE THREAD

**Issue by hp1361** [sajaddp/list-of-cities-in-Iran#7]
سلام
کار خیلی خوبی انجام دادید
پیشنهادم اینه که ترتیب استان ها، مطابق ترتیبی باشه که سایت مرکز آمار قرار داده است. برای نمونه شماره ID استان گلستان 27 می باشد که شما 24 امین رکورد قرار داده اید.

**Comment by sajaddp** [comment]
@hp1361 

سلام
ایده خوبی هست. اما یک موضوع وجود دارد، اینکه دوستانی که قبلا از این فایل استفاده کرده اند برای بروزرسانی های بعدی لیست شهرها دچار مشکل می شوند.

اما احتمالا بتوانیم نگارش فعلی را در کنار نگارش مرکز آمار یکجا نگه داری کنیم.

ممنون می شوم اگر آدرس داده های سایت مرکز آمار را بفرمایید.

**Comment by hp1361** [comment]
https://www.amar.org.ir/%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7-%D8%A8%D8%A7-%D9%85%D8%A7/%D8%AA%D9%82%D8%B3%DB%8C%D9%85%D8%A7%D8%AA-%DA%A9%D8%B4%D9%88%D8%B1%DB%8C
