### ISSUE TITLE
ویرایش جزئی و استفاده از نیم‌فاصله

### ISSUE THREAD

**Issue by esmaeelE** [sajaddp/list-of-cities-in-Iran#9]
در Readme از نیم‌فاصله استفاده کنید خواناتر می‌شود.

**Comment by sajaddp** [comment]
در #15 چند مورد را اصلاح کردم. برخی موارد به علت اینکه دقیقا مانند جستجوی دوستان در موتورهای جستجوگر باشد عمدا به جای نیم‌فاصله از فاصله استفاده شده.
